[general]
import = ["~/.config/alacritty/themes/kanagawa.toml"]

[font]
size = 15.0

[window.padding]
x = 20
y = 20

[window]
dimensions = { columns = 100, lines = 37 }
opacity = 1
blur = true

# Cursor style
[cursor]
style = "Block"
unfocused_hollow = true
